### ISSUE TITLE
on android unfilled part is not comming.

### ISSUE THREAD

**Issue by prakashkrsingh09** [lorenc-tomasz/react-native-simple-gradient-progressbar-view#1]
![photo_2022-07-15 17 22 12](https://user-images.githubusercontent.com/50052191/179217979-f7d4c85d-b6e3-4109-841e-baad47c6320b.jpeg)
in the progress bar, the unfiled part is not showing on android. but on ios, it is working fine.

**Comment by lorenc-tomasz** [comment]
@prakashkrsingh0 Hi,
thanks for feedback. The iOS basic implementation of custom view is different. Some props are inherited by default from base view on iOS. On Android - not.

Honestly I don't have currently time to implement border on Android side as it's not necessary. You achieve the border both on iOS and Android by wrapping the progress bar with other view with border params. I have done it that way in my own project. Working fine :) 

I always happy to see PR that would resolve this lack of functionality.
